[package]
name = "cfgmap"
version = "0.1.0"
authors = ["Calmynt <mctech26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cfgmap"
path = "src/cfgmap.rs"

[dependencies]